import { useEffect, useMemo, useState } from "react";
import { Plus, Search } from "lucide-react";
import { Badge, Button, Card, Field, Input, Modal, Table, useToast } from "../../components/ui/index.js";
import { supabase } from "../../lib/supabaseClient.js";
import { isValidSubdomain, sanitizeSubdomain, sanitizeText } from "../../lib/validation.js";

export default function HospitalsPage() {
  const toast = useToast(); const [rows,setRows]=useState([]); const [loading,setLoading]=useState(true); const [search,setSearch]=useState(""); const [open,setOpen]=useState(false); const [form,setForm]=useState({name:"",subdomain:""}); const [saving,setSaving]=useState(false);
  async function load(){if(!supabase){toast.error("Supabase কনফিগার করা নেই");setLoading(false);return;} const {data,error}=await supabase.from("hospitals").select("*").order("created_at",{ascending:false}); if(error) toast.error(error.message); setRows(data||[]);setLoading(false);}
  useEffect(()=>{load();},[]); const filtered=useMemo(()=>rows.filter(row=>`${row.name} ${row.subdomain}`.toLowerCase().includes(search.toLowerCase())),[rows,search]);
  async function create(event){event.preventDefault();const subdomain=sanitizeSubdomain(form.subdomain);const name=sanitizeText(form.name,120);if(!name||!isValidSubdomain(subdomain))return toast.error("নাম এবং lowercase letter, number ও single hyphen-এর subdomain দিন।");setSaving(true);const {error}=await supabase.from("hospitals").insert({name,subdomain,status:"trial"});setSaving(false);if(error)toast.error(error.message);else{toast.success("হাসপাতাল তৈরি হয়েছে।");setOpen(false);setForm({name:"",subdomain:""});load();}}
  async function toggle(row){const status=row.status==="suspended"?"active":"suspended";const {error}=await supabase.from("hospitals").update({status}).eq("id",row.id);error?toast.error(error.message):(toast.success(`Status ${status} হয়েছে।`),load());}
  const columns=[{key:"name",label:"Hospital",sortable:true},{key:"subdomain",label:"Subdomain",sortable:true},{key:"status",label:"Status",render:row=><Badge variant={row.status==="active"?"success":row.status==="suspended"?"danger":"warning"}>{row.status}</Badge>},{key:"created_at",label:"Signup",sortable:true,render:row=>new Date(row.created_at).toLocaleDateString("bn-BD")},{key:"actions",label:"",render:row=><Button size="sm" variant={row.status==="suspended"?"primary":"danger"} onClick={()=>toggle(row)}>{row.status==="suspended"?"Activate":"Suspend"}</Button>}];
  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="caption font-semibold text-primary-600">Tenant management</p><h1 className="mt-1 text-3xl">Hospitals</h1></div><Button onClick={()=>setOpen(true)}><Plus className="size-4"/> নতুন হাসপাতাল</Button></div><Card className="mt-6 overflow-hidden"><div className="border-b border-primary-100 p-4"><label className="relative block max-w-md"><Search className="absolute left-3 top-3 size-4 text-primary-400"/><Input aria-label="হাসপাতাল খুঁজুন" className="pl-9" placeholder="নাম বা subdomain" value={search} onChange={e=>setSearch(e.target.value)}/></label></div>{loading?<div className="p-8 text-primary-500">লোড হচ্ছে…</div>:<Table columns={columns} data={filtered}/>}</Card><Modal open={open} onClose={()=>setOpen(false)} title="নতুন হাসপাতাল"><form onSubmit={create} className="space-y-4"><Field label="হাসপাতালের নাম" required><Input required maxLength={120} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Subdomain" required hint="lowercase-letter-number-hyphen"><Input required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value={form.subdomain} onChange={e=>setForm({...form,subdomain:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,"")})}/></Field><Button type="submit" loading={saving}>তৈরি করুন</Button></form></Modal></div>;
}
