import { useEffect, useState } from "react";
import { CalendarDays, Phone } from "lucide-react";
import { Badge, Button, Card, ConfirmDialog, EmptyState, Skeleton, Tabs, Textarea, useToast } from "../../components/ui/index.js";
import { useAuth } from "../../context/AuthContext.jsx";
import { getAppointments, updateAppointmentStatus } from "../../lib/api/appointments.js";

const tabs = [{ value: "pending", label: "Pending" }, { value: "approved", label: "Approved" }, { value: "rejected", label: "Rejected" }, { value: "all", label: "All" }];
const badge = { pending: "warning", approved: "success", rejected: "danger" };
export default function AppointmentsPanel() {
  const { hospitalId } = useAuth(); const toast = useToast(); const [status, setStatus] = useState("pending"); const [rows, setRows] = useState(null); const [target, setTarget] = useState(null); const [note, setNote] = useState(""); const [saving, setSaving] = useState(false);
  async function load() { setRows(null); const { data, error } = await getAppointments(hospitalId, status); if (error) toast.error(error.message); setRows(data || []); }
  useEffect(() => { if (hospitalId) load(); }, [hospitalId, status]);
  async function confirm() { setSaving(true); const { error } = await updateAppointmentStatus(hospitalId, target.row.id, target.next, note); setSaving(false); if (error) toast.error(error.message); else { toast.success(`অ্যাপয়েন্টমেন্ট ${target.next === "approved" ? "অনুমোদিত" : "প্রত্যাখ্যাত"} হয়েছে।`); setTarget(null); setNote(""); load(); } }
  return <div><p className="caption font-semibold text-primary-600">রোগীর অনুরোধ</p><h1 className="mt-1 text-3xl">অ্যাপয়েন্টমেন্ট</h1><div className="mt-6"><Tabs tabs={tabs} value={status} onChange={setStatus} /></div><div className="mt-5 space-y-4">{rows === null ? <><Skeleton className="h-40" /><Skeleton className="h-40" /></> : rows.length === 0 ? <Card><EmptyState title="এই status-এ কোনো অ্যাপয়েন্টমেন্ট নেই" description="নতুন request এলে এই তালিকায় দেখা যাবে।" /></Card> : rows.map((row) => <Card key={row.id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-xl">{row.name}</h3><Badge variant={badge[row.status] || "neutral"}>{row.status}</Badge></div><a className="mt-2 inline-flex items-center gap-2 text-sm text-primary-600" href={`tel:${row.mobile}`}><Phone className="size-4" />{row.mobile}</a><p className="mt-2 flex items-center gap-2 text-sm text-primary-500"><CalendarDays className="size-4" />{row.preferred_date || "তারিখ নেই"} {row.preferred_time || ""}</p><p className="mt-3 text-primary-600">ডাক্তার: {row.doctors?.name?.bn || row.doctors?.name?.en || "যেকোনো"}</p>{row.problem && <p className="mt-2 text-primary-500">{row.problem}</p>}</div>{row.status === "pending" && <div className="flex gap-2"><Button size="sm" onClick={() => setTarget({ row, next: "approved" })}>Approve</Button><Button size="sm" variant="danger" onClick={() => setTarget({ row, next: "rejected" })}>Reject</Button></div>}</div>{row.admin_note && <p className="mt-4 rounded-lg bg-primary-50 p-3 text-sm text-primary-600">Admin note: {row.admin_note}</p>}</Card>)}</div><ConfirmDialog open={Boolean(target)} title={target?.next === "approved" ? "অনুমোদন নিশ্চিত করুন" : "প্রত্যাখ্যান নিশ্চিত করুন"} confirmLabel={target?.next === "approved" ? "Approve" : "Reject"} danger={target?.next === "rejected"} loading={saving} onCancel={() => { setTarget(null); setNote(""); }} onConfirm={confirm}><label className="mt-4 block text-sm font-semibold text-primary-700">নোট (ঐচ্ছিক)<Textarea className="mt-1" placeholder="উদাহরণ: রোগীকে ফোনে সময় নিশ্চিত করা হয়েছে।" value={note} maxLength={500} onChange={(e) => setNote(e.target.value)} /></label></ConfirmDialog></div>;
}
