import { useEffect, useMemo, useState } from "react";
import { Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Card, EmptyState, Skeleton, Table } from "../../components/ui/index.js";
import { useAuth } from "../../context/AuthContext.jsx";
import { supabase } from "../../lib/supabaseClient.js";

export default function HospitalAnalyticsPage() {
  const { hospitalId } = useAuth(); const [state, setState] = useState(null);
  useEffect(() => { if (!supabase || !hospitalId) { setState({ events: [], doctors: [], services: [] }); return; } const since = new Date(Date.now() - 30 * 864e5).toISOString(); Promise.all([supabase.from("analytics_events").select("event_type,entity_type,entity_id").eq("hospital_id", hospitalId).gte("created_at", since).in("event_type", ["doctor_view","doctor_save","service_view"]), supabase.from("doctors").select("id,name").eq("hospital_id", hospitalId), supabase.from("services").select("id,name").eq("hospital_id", hospitalId)]).then(([events,doctors,services]) => setState({ events: events.data || [], doctors: doctors.data || [], services: services.data || [] })); }, [hospitalId]);
  const analytics = useMemo(() => { if (!state) return null; const name = (value) => value?.bn || value?.en || "নাম নেই"; const doctorCounts = Object.fromEntries(state.doctors.map((d) => [String(d.id), { name: name(d.name), views: 0, saves: 0 }])); const serviceCounts = Object.fromEntries(state.services.map((s) => [String(s.id), { id: s.id, name: name(s.name), views: 0 }])); state.events.forEach((e) => { if (e.event_type === "doctor_view" && doctorCounts[e.entity_id]) doctorCounts[e.entity_id].views += 1; if (e.event_type === "doctor_save" && doctorCounts[e.entity_id]) doctorCounts[e.entity_id].saves += 1; if (e.event_type === "service_view" && serviceCounts[e.entity_id]) serviceCounts[e.entity_id].views += 1; }); return { doctors: Object.values(doctorCounts).sort((a,b) => b.views-a.views).slice(0,10), services: Object.values(serviceCounts).sort((a,b) => b.views-a.views) }; }, [state]);
  if (!analytics) return <Skeleton className="h-80" />;
  return <div><p className="caption font-semibold text-primary-600">গত ৩০ দিন</p><h1 className="mt-1 text-3xl">Hospital Analytics</h1><div className="mt-6 grid gap-6 xl:grid-cols-2"><Card className="p-5"><h2 className="text-xl">ডাক্তার engagement</h2>{analytics.doctors.length ? <div className="mt-5 h-80"><ResponsiveContainer width="100%" height="100%"><BarChart data={analytics.doctors} layout="vertical" margin={{ left: 20 }}><CartesianGrid strokeDasharray="3 3" horizontal={false} /><XAxis type="number" allowDecimals={false} /><YAxis dataKey="name" type="category" width={100} tick={{ fontSize: 12 }} /><Tooltip /><Legend /><Bar dataKey="views" name="Views" fill="#33443f" radius={[0,4,4,0]} /><Bar dataKey="saves" name="Saves" fill="#D9A24B" radius={[0,4,4,0]} /></BarChart></ResponsiveContainer></div> : <EmptyState title="এখনো analytics event নেই" />}</Card><Card className="overflow-hidden"><div className="p-5"><h2 className="text-xl">সার্ভিস view ranking</h2></div><Table data={analytics.services} columns={[{ key:"name", label:"সার্ভিস", sortable:true }, { key:"views", label:"Views", sortable:true }]} /></Card></div></div>;
}
